[general]
name = "minilib-xml"
version = "0.7.1"
fix_version = "1.5.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "lib/encoding/xml.fix",
    "lib/encoding/xml/xml_helpers.fix",
    "lib/encoding/xml/xml_parser.fix",
]

[build.test]
opt_level = "basic"
files = [
    "tests/test.fix",
    "tests/encoding/xml/xml_helpers_test.fix",
    "tests/encoding/xml/xml_parser_test.fix",
    "tests/encoding/xml_test.fix",
]

[[dependencies]]
name = "character"
version = "1.0.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-character.git" }

[[dependencies]]
name = "minilib-common"
version = "0.14.0"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }

[[dependencies]]
name = "minilib-text"
version = "0.10.1"
# path = "../fixlang-minilib-text"
git = { url = "https://github.com/pt9999/fixlang-minilib-text.git" }

[[dependencies]]
name = "minilib-binary"
version = "0.7.2"
# path = "../fixlang-minilib-binary"
git = { url = "https://github.com/pt9999/fixlang-minilib-binary.git" }

